# Generated by Django 3.2.25 on 2024-08-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_note',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
