# Generated by Django 3.2.25 on 2024-08-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
    ]
