# Generated by Django 3.2.25 on 2024-08-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
